pluginManagement {
	resolutionStrategy {
		eachPlugin {
			if (requested.id.id == 'net.fabricmc.fabric-loom-remap') {
				useModule('net.fabricmc:fabric-loom:1.17.20')
			}
		}
	}
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = "madoku-craft-utility"



if (gradle.parent == null) {
	includeBuild("../core")
}
